In [1]:
# Useful starting lines
%matplotlib inline

import numpy as np
import scipy
import scipy.io
import scipy.sparse as sp
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.

Implement the sigmoid activation function.

In [3]:
def sigmoid(t):
    """Apply sigmoid function on t.

    Args:
        t: scalar or numpy array

    Returns:
        scalar or numpy array

    >>> sigmoid(np.array([0.1]))
    array([0.52497919])
    >>> sigmoid(np.array([0.1, 0.1]))
    array([0.52497919, 0.52497919])
    """
    return 1/(1 + np.exp(-t))
    
def grad_sigmoid(t):
    """Return the gradient of sigmoid on t.
    
    Args:
        t: scalar or numpy array
        
    Returns:
        scalar or numpy array
        
    >>> grad_sigmoid(np.array([0.1]))
    array([0.24937604])
    >>> grad_sigmoid(np.array([0.1, 0.1]))
    array([0.24937604, 0.24937604])
    """
    e_mint = np.exp(-t)
    
    return e_mint/(1 + e_mint)**2

In [4]:
sigmoid(np.array([0.1]))

array([0.52497919])

In [5]:
sigmoid(np.array([0.1, 0.1]))

array([0.52497919, 0.52497919])

In [6]:
grad_sigmoid(np.array([0.1]))

array([0.24937604])

In [8]:
grad_sigmoid(np.array([0.1, 0.1]))

array([0.24937604, 0.24937604])

Note that you are working on a three-layer neural network with one input layer of size $D=4$, $L=1$ hidden layer with size $K=5$, and one output layer with size 1.

Initialize the data.

In [9]:
x = np.array([0.01, 0.02, 0.03, 0.04])
W = {
    "w_1": np.ones((4, 5)),
    "w_2": np.ones(5)
}
y = 1

# Problem 1: Feed-forward in neural network

Implement the neural network described by Equation 1 of the exercise sheet.

In [33]:
def simple_feed_forward(x, W):
    """Do feed-forward propagation.
    
    Args:
        x: numpy array of shape (D, )
        W: a dictionary of numpy array, with two elements, w_1 and w_2.
            w_1: shape=(D, K)
            w_2: shape=(K, )
        
    Returns:
        z1: a numpy array, generated from the hidden layer (before the sigmoid function) 
        z2: scalar number, generated from the output layer (before the sigmoid function)
        y_hat: a scalar (after the sigmoid function)
        
    >>> np.array([0.01, 0.02, 0.03, 0.04])
    >>> W = {
        "w_1": np.ones((4, 5)),
        "w_2": np.ones(5)
    }
    >>> z1, z2, y_hat = simple_feed_forward(x, W)
    >>> z1
    array([0.1, 0.1, 0.1, 0.1, 0.1])
    >>> z2
    2.6248959373947
    >>> y_hat
    0.932446754272157
    """
    z1 = W['w_1'].T.dot(x)
    x1 = sigmoid(z1)
    z2 = np.sum(W['w_2']*x1)
    y_hat = sigmoid(z2)
    return z1, z2, y_hat

expected = 0.93244675427215695
z1, z2, yours = simple_feed_forward(x, W)
try:
    assert np.sum((yours - expected) ** 2) < 1e-15
    print("Your implementation is correct!")
except:
    print("Your implementation is not correct.")

Your implementation is correct!


# Problem 2: Backpropagation in neural network

Implement your derivation of backpropagation. 

*Hint*: You might want to slightly change `simple_feed_forward`.

In [76]:
def simple_backpropagation(y, x, W):
    """Do backpropagation and get delta_W.
    
    Args:
        y: scalar number
        x: numpy array of shape (D, )
        W: a dictionary of numpy array, with two elements, w_1 and w_2.
            w_1: shape=(D, K)
            w_2: shape=(K, )
        
    Returns:
        grad_W: a dictionary of numpy array. It corresponds to the gradient of weights in W.
        
        
    >>> y = 1
    >>> np.array([0.01, 0.02, 0.03, 0.04])
    >>> W = {
        "w_1": np.ones((4, 5)),
        "w_2": np.ones(5)
    }
    >>> grad_W = simple_backpropagation(y, x, W)
    """
    z1, z2, y_hat = simple_feed_forward(x, W)
    delta_2 = (y_hat - y) * grad_sigmoid(z2)
    delta_w_2 = delta_2 * sigmoid(z1)
    delta_1 = W['w_2'] * delta_2 * grad_sigmoid(z1) # shape (5,)
    x = np.reshape(x, (len(x),1))
    delta_w_1 = x.dot(np.reshape(delta_1, (1, len(delta_1))))

    return {
        "w_1": delta_w_1,
        "w_2": delta_w_2
    }
  
yours = simple_backpropagation(y, x, W)  
print(yours)
try:
    expected = {
        'w_1': np.array([
            [ -1.06113639e-05,  -1.06113639e-05,  -1.06113639e-05, -1.06113639e-05,  -1.06113639e-05],
            [ -2.12227277e-05,  -2.12227277e-05,  -2.12227277e-05, -2.12227277e-05,  -2.12227277e-05],
            [ -3.18340916e-05,  -3.18340916e-05,  -3.18340916e-05, -3.18340916e-05,  -3.18340916e-05],
            [ -4.24454555e-05,  -4.24454555e-05,  -4.24454555e-05, -4.24454555e-05,  -4.24454555e-05]]),
        'w_2': np.array(
            [-0.00223387, -0.00223387, -0.00223387, -0.00223387, -0.00223387])
    }
    assert np.sum(
        [np.sum((yours[key] - expected[key]) ** 2)
         for key in expected.keys()]) < 1e-15
    print("Your implementation is correct!")
except:
    print("Your implementation is not correct!")

{'w_1': array([[-1.06113639e-05, -1.06113639e-05, -1.06113639e-05,
        -1.06113639e-05, -1.06113639e-05],
       [-2.12227277e-05, -2.12227277e-05, -2.12227277e-05,
        -2.12227277e-05, -2.12227277e-05],
       [-3.18340916e-05, -3.18340916e-05, -3.18340916e-05,
        -3.18340916e-05, -3.18340916e-05],
       [-4.24454555e-05, -4.24454555e-05, -4.24454555e-05,
        -4.24454555e-05, -4.24454555e-05]]), 'w_2': array([-0.00223387, -0.00223387, -0.00223387, -0.00223387, -0.00223387])}
Your implementation is correct!
